services:
  - type: web
    name: prospectiq-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: NODE_VERSION
        value: 18
